EsraBlog/Controllers/HakkımdaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EsraBlog.data;
namespace EsraBlog.Controllers
{
    public class HakkımdaController : Controller
    {
        
        public ActionResult Index()
        {
            
           
            return View();
        }

      

     
    }
}

EsraBlog/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EsraBlog.data;
namespace EsraBlog.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult SonBesMakale()
        {
            
            EsraBlogcontext db = new EsraBlogcontext();

       
           
            List<Makale> makaleListe = db.Makales.OrderByDescending(i => i.Tarih).Take(5).ToList();

           
            return PartialView(makaleListe);
        }

        public ActionResult SonBesYorum()
        {
            EsraBlogcontext db = new EsraBlogcontext();

          
            List<Yorum> yorumListe = db.Yorums.OrderByDescending(i => i.Tarih).Take(5).ToList();

            
            return PartialView(yorumListe);

        }
        public ActionResult MakaleDetay(int makaleId)
        {
            EsraBlogcontext db = new EsraBlogcontext();

       
            Makale makale = (from i in db.Makales where i.MakaleId == makaleId select i).SingleOrDefault();
            return View(makale);
        }
        public ActionResult YorumMakalesi(int yorumId)
        {
            EsraBlogcontext db = new EsraBlogcontext();

            Makale makale = (from i in db.Yorums where i.YorumId == yorumId select i.Makale).SingleOrDefault();
            return View(makale);
        }
     
    }
}

EsraBlog/Controllers/UyelikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EsraBlog.data;
namespace EsraBlog.Controllers
{
    public class UyelikController : Controller
    {
        // GET: Uyelik
        public ActionResult YeniUyelik()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniUyelik(uye model, string textBoxDogum, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            if (String.IsNullOrEmpty(textBoxDogum))
            {
                ModelState.AddModelError("textBoxDogum", "Doğum tarihi boş geçilemez");

                return View();
            }
            int yil = int.Parse(textBoxDogum.Substring(6));
            if (yil > 2002)
            {
                ModelState.AddModelError("textBoxDogum", "Yaşınız 12 den küçük olamaz");
                return View();
            }
            uye uye = new uye();
            if (file != null)
            {
               
                file.SaveAs(Server.MapPath("~/Images/") + file.FileName);
                uye.ResimYol = "/Images/" + file.FileName;
            }
            uye.Ad = model.Ad;
            uye.EPosta = model.EPosta;
            uye.Soyad = model.Soyad;
            uye.UyeOlmaTarih = DateTime.Now;
            uye.WebSite = model.WebSite;
            uye.Sifre = model.Sifre;
            using (EsraBlogcontext db = new EsraBlogcontext())
            {
                db.Uyes.Add(uye);
                db.SaveChanges();

                return RedirectToAction("UyelikBasarili");
            }
        }

        public ActionResult UyelikBasarili()
        {
            return View();
        }

        public ActionResult UyeGiris()
        {
            return View();
        }

        [HttpPost]
        public string UyeGirisi()
        {
            
        
            string posta = Request.Form["txtPosta"];
            string sifre = Request.Form["pswSifre"];
            if (String.IsNullOrEmpty(posta) && String.IsNullOrEmpty(sifre))
            {
                return "E-Posta adresinizi ve şifrenizi girmediniz.";
            }
            else if (String.IsNullOrEmpty(posta))
            {
                return "E-posta adresinizi girmediniz.";
            }
            else if (string.IsNullOrEmpty(sifre))
            {
                return "Şifrenizi girmediniz.";
            }
            else
            {
                using (EsraBlogcontext db = new EsraBlogcontext())
                {
                  
                    var uye = (from i in db.Uyes where i.Sifre == sifre && i.EPosta == posta select i).SingleOrDefault();

                    if (uye == null) return "Kullanıcı adınızı ya da şifreyi hatalı girdiniz.";

                    
                    Session["uyeId"] = uye.UyeId;

                    
                    return "Sisteme, başarıyla giriş yaptınız.<script type='text/javascript'>setTimeout(function(){window.location='/'},3000);</script>";
                }
            }
        }
    }
}

EsraBlog/Views/Hakkımda/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<h2>
    <br>
    <img src="~/Images/adminresmi/DSC03190.jpg" alt="PROFİL RESMİ" border="0" align="left" height="400" width="400">
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><strong>Hakkımda</strong></h2>
    <h3>
        <br><br>
        <strong>
            Adım:
        </strong>ESRA ÜZÜM<br><br>
        <strong>
            ÜNİVERSİTE:
        </strong>YILDIRIM BEYAZIT ÜNİVERSİTESİ<br><br>
        <strong>
            BÖLÜM:
        </strong>
        BİLGİSAYAR MÜH.<br><br>
        <strong>
            İLETİŞİM:
        </strong>esra_uzum_19@hotmail.com<br>


    </h3>

EsraBlog/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<div style="width:75%;float:left">
    
    @Html.Action("SonBesMakale")
</div>
<div style="width:25%;float:left">
    @Html.Action("SonBesYorum")
</div>

EsraBlog/Views/Home/MakaleDetay.cshtml
@model EsraBlog.data.Makale

@{
    ViewBag.Title = "MakaleDetay";
}

<h2>MakaleDetay</h2>

<div style="width:100%;margin-top:25px;box-shadow:0 0 5px gray;padding:25px;">
    
    <h3 style="font-weight:bold;color:red">
        @Html.DisplayFor(i => Model.Baslik)
{
        <img src="~/Images/adminresmi/Amsterdam3.jpg" alt="AMSTERDAM" border="0" align="left" height="400" width="1100"><br>
        <br>
        <br>
        <br>
        <br>
        }
    </h3>
   
    <hr />

    @Html.DisplayFor(i => Model.Icerik)
    <h4>Makale içeriği, zaman yetersizliğinden dolayı henüz eklenememiştir, en yakın zamanda eklemeye çalışacağım.</h4>

<hr />

@Html.Label("Tarih : ")

@Html.DisplayFor(i => Model.Tarih)
<hr />
<h4>Makaleyi Yazan</h4>

    <
@{string adSoyad = Model.Uye.Ad + " " + Model.Uye.Soyad;}
@Html.Label("Adı ve Soyadı : ")&nbsp;&nbsp;@adSoyad
</div>

EsraBlog/Views/Home/SonBesMakale.cshtml
@model List<EsraBlog.data.Makale>

@{
    <h2>MAKALELER:</h2>    
   
    <div style="border:1px solid black;padding:25px;text-align:center;">
        
       
        @foreach (var item in Model)
        {

            <div style="border:1px solid black">
                @Html.ActionLink(item.Baslik, "MakaleDetay", new { makaleId = item.MakaleId })

                <p>@item.Icerik</p>

               
        
                <strong>Tarih : @item.Tarih </strong>

            </div>
        }
        
    </div>
    <img src="~/Images/adminresmi/Gırnata.jpg" alt="Granada" border="0" align="left" height="750" width="1350">
}

EsraBlog/Views/Home/SonBesYorum.cshtml
@model List<EsraBlog.data.Yorum>
<div style="border:1px solid red;padding:25px;text-align:center;">
    <h2>Son Beş Yorum</h2>
    @{
        
        for (int i = 0; i < Model.Count() - 1; i++)
        {
           
            <div style="border:1px solid red">
                
                <h3>Üye Bilgileri</h3>
                Adı : @Model[i].Uye.Ad<br />
                Soyadı : @Model[i].Uye.Soyad<br />
                <h3>Makale Bilgileri</h3>
                
                Başlık : @Html.ActionLink(@Model[i].Makale.Baslik, "YorumMakalesi", new { yorumId = Model[i].YorumId })
                <h3>Yorumun İçeriği</h3>
                <p>@Model[i].Icerik</p>
                Tarih : @Model[i].Tarih
            </div>
        }
    }
</div>

EsraBlog/Views/Home/YorumMakalesi.cshtml
@model EsraBlog.data.Makale

@{
    ViewBag.Title = "YorumMakalesi";
}


<h2>Makale Detayı</h2>

<div style="width:100%;margin-top:25px;box-shadow:0 0 5px gray;padding:25px;">
    <!--Başlığı, büyük ve renkli görünsün diye, h3 tagı içerisine aldık-->
    <h3 style="font-weight:bold;color:red">
        @Html.DisplayFor(i => Model.Baslik)
    </h3>

    <!--Başlıkla içerik arasına, dikey çizgi ekliyoruz.-->
    <hr />

    @Html.DisplayFor(i => Model.Icerik)
    <hr />
    <!--Tarih başlığını, tarih içeriğine bağlamak için Label kullandık.-->
    @Html.Label("Tarih : ")

    @Html.DisplayFor(i => Model.Tarih)
    <hr />
    <h4>Makaleyi Yazan</h4>

    <!--Burada bir değişkende, ad ile soyadı birleştirip ekrana bastık.-->
    @{string adSoyad = Model.Uye.Ad + " " + Model.Uye.Soyad;}
    @Html.Label("Adı ve Soyadı : ")&nbsp;&nbsp;@adSoyad
</div>

EsraBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Esra ÜZÜM's Blog", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ana Sayfa", "Index", "Home")</li>
                    <li>@Html.ActionLink("Hakkımda", "Index", "Hakkımda")</li>
                  
                   
                    <li>@Html.ActionLink("Üye Girişi", "UyeGiris", "Uyelik")</li>
                    <li>@Html.ActionLink("Yeni Üyelik", "YeniUyelik", "Uyelik")</li>
                </ul>
             
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ilk deneyim...</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
   
</body>
</html>

EsraBlog/Views/Uyelik/UyeGiris.cshtml
@{
    ViewBag.Title = "UyeGiris";
}

@section scripts{
    <style type="text/css">
        #formKapsayici {
            box-shadow: 0 0 5px gray;
            padding: 25px;
            height: 500px;
        }

        #divSol, #divSag {
            float: left;
            margin-left: 25px;
        }

            #divSol *, #divSag * {
                margin-top: 15px;
            }

        input[type="text"] {
            width: 250px;
        }

        #btnUyeOl {
            /*clear komutu ile önceki divlerin sola yaslanarak sıralanmasında, butonun bu yaslanmaya
            uymayıp alt satıra inmesini sağlıyoruz*/
            clear: both;
            display: block;
            margin-left: 132px;
        }

        #divSonuc {
            color: red;
        }
    </style>
}
<h2>Üye Girişi</h2>
@using (Ajax.BeginForm("UyeGirisi", "Uyelik", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "divSonuc" }, new { id = "formKapsayici" }))
{
    <div id="divSol">
        @Html.Label("E-Posta Adresiniz")<br />
        @Html.Label("Şifreniz")
    </div>
    <div id="divSag">
        : @Html.TextBox("txtPosta")<br />
        : @Html.Password("pswSifre")
    </div>
    <input type="submit" value="Üye Ol" id="btnUyeOl" />
    <div id="divSonuc"></div>
}

EsraBlog/Views/Uyelik/YeniUyelik.cshtml
@model EsraBlog.data.uye

@{
    ViewBag.Title = "YeniUyelik";
}

@section scripts{
    <style type="text/css">
        #formKapsayici {
            box-shadow: 0 0 5px gray;
            padding: 25px;
            height: 500px;
        }

        #divSol, #divSag {
            float: left;
            margin-left: 25px;
        }

            #divSol *, #divSag * {
                margin-top: 15px;
            }

        input[type="text"] {
            width: 250px;
        }

        #btnUyeOl {
           
            clear: both;
            display: block;
            margin-left: 132px;
        }
    </style>

  
    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css" />
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
   
    <script type="text/javascript">
        $(document).ready(function () {
            $("#textBoxDogum").datepicker();
        });
    </script>
}
<h2>Yeni Üyelik</h2>


@using (Html.BeginForm("YeniUyelik", "Uyelik", FormMethod.Post, new { enctype = "multipart/form-data", id = "formKapsayici" }))
{
    <div id="divSol">
        @Html.LabelFor(i => Model.Ad)<br /><br />
        @Html.LabelFor(i => Model.Soyad)<br /><br />
        @Html.LabelFor(i => Model.EPosta)<br /><br />
        @Html.LabelFor(i => Model.Sifre)<br /><br />
        @Html.LabelFor(i => Model.WebSite)<br /><br />

      
        @Html.Label("Doğum Tarihiniz")<br /><br />
        @Html.Label("Profil Resminiz")<br /><br />
    </div>
    <div id="divSag">
        : @Html.TextBoxFor(i => Model.Ad)<br /><br />
        : @Html.TextBoxFor(i => Model.Soyad)<br /><br />
        : @Html.TextBoxFor(i => Model.EPosta)<br /><br />
        : @Html.TextBoxFor(i => Model.Sifre)<br /><br />
        : @Html.TextBoxFor(i => Model.WebSite)<br /><br />
        : @Html.TextBox("textBoxDogum")<br /><br />

        <input type="file" id="inputFile" name="file" /> <br /><br />

    </div>
    <input type="submit" value="Üye Ol" id="btnUyeOl" />

    @Html.ValidationSummary()
}